### PR TITLE
Pass key to computedPromise

### PR DESCRIPTION
**Pull request by knownasilya**
So we know which key triggered the CP

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1: - Failures are likely due to jQuery version issue.

**Comment by cibernox** [comment]
jQuery version? Wut?

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/issues/5316

**Comment by cibernox** [comment]
Cleaning this. I don't know why it failed but after  year of not merging this perhaps it doesn't make sense anymore

**Pull request closed without merging**
