### PR TITLE
Use EmberString.htmlSafe for handling html escape

### PR DESCRIPTION
**Pull request by tennisonchan**
This Pr is to use `Ember.String.htmlSafe` to handle safe string parsing to html, since `Ember.Handlebars.SafeString` is deprecated in favor of `Ember.String.htmlSafe` in Ember version 2.8.

### CODE REVIEW

**Comment by tennisonchan** [comment]
Hey @cibernox, not sure if you want to lockstep with Ember version 2.8, or use things like `var htmlSafe = Ember.String.htmlSafe && Ember.Handlebars.SafeString`. Please let me know. Will update this PR accordingly.

**Comment by cibernox** [comment]
I think that `Ember.String.htmlSafe` has been there for ages, at least since 2014, so it's safe to just use it.

**Comment by tennisonchan** [comment]
The tests failed on version 2.0.1 and lower. Any thoughts?

**Comment by cibernox** [comment]
No idea, but I really need to make this addon idiomatic. I'll do it tomorrow.

**Comment by cibernox** [comment]
@tennisonchan Can you rebase over master? I think I've fixed tests.

**Comment by tennisonchan** [comment]
@cibernox The tests passed! Awesome!!!

**Comment by cibernox** [comment]
Thanks! I've just released a new version.

**Pull request merged**
