### PR TITLE
[WIP] Update addon via `ember init`

### PR DESCRIPTION
**Pull request by elwayman02**
Tests are failing.

### CODE REVIEW

**Comment by elwayman02** [comment]
Seems that the setters for the CPs aren't working. See `as-float-test` for examples.

**Comment by elwayman02** [comment]
Also, some computed got removed from Ember that Ember-CPM relies on (or at least has tests that rely on).

http://emberjs.com/api/classes/Ember.computed.html

^note the lack of `computed.any`, which is used in `conditional-test`

**Comment by elwayman02** [comment]
It doesn't seem like any of the actual addon code leverages Ember.computed.any, so maybe we should just remove the tests that were testing against it?

**Comment by elwayman02** [comment]
Also, array polyfills were removed in Ember 2.x somewhere, so we should use lodash for tests or just do manual for-loops.

**Comment by cibernox** [comment]
Thanks for the effort. I'll review this (and finish it) during the weekend :)

**Comment by elwayman02** [comment]
@cibernox is this good to go?

**Comment by cibernox** [comment]
@elwayman02 Yep. Going in.

**Comment by cibernox** [comment]
I'd like check a couple more things, but I'll release 2.0 soon.

**Pull request merged**
